---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-monetdb
  namespace: kooplex-veo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10T
  storageClassName: example-nfs
