---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-raw
  namespace: kooplex-veo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: example-nfs
